Repository uport-project/developers, pull requests merged in 2018-08, with the labels that each got.

#74 Responsive adjustments for tablet
  src/components/Layout/Header.jsx
  src/components/Layout/Navigation.jsx
  src/layouts/theme.js
  src/pages/index.jsx
  src/templates/content.jsx
Labels: review

#75 Feature/reorder documentation
  gulp/copy.js
  repos.json
  src/components/BuildingBlocks.js
Labels: review

#68 App Configuration Wizard
  gatsby-config.js
  package-lock.json
  package.json
  src/components/Demo.jsx
  src/images/start-building.svg
  src/layouts/css/appmanager.css
  src/pages/appmanager/getstarted.js
  src/pages/appmanager/index.js
  src/pages/appmanager/sample-code.js
  src/pages/appmanager/startbuilding.js
  src/state/configureStore.js
Labels: review, work in progress

#82 Dropping target=_blank on App Manager link
  src/components/Layout/Navigation.jsx
Labels: review

#84 Skip start screen if already logged in
  src/pages/appmanager/index.js
Labels: review

#83 Fix App Details link, and filling form values from redux state
  src/pages/appmanager/index.js
  src/pages/appmanager/sample-code.js
  src/pages/appmanager/startbuilding.js
Labels: review

#88 Adding survey for content feedback
  src/components/Survey.jsx
  src/layouts/css/index.css
  src/templates/content.jsx
Labels: review, review needed

#94 Update attest credentials guide
  markdown/docs/guides/AttestCredentials.md
Labels: review

#96 Update request credentials guide
  markdown/docs/guides/RequestCredentials.md
Labels: review

#95 Update signing transactions guide
  markdown/docs/guides/SignTransactions.md
Labels: review
